services:
  mongodb.web:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb.web
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  spotquoteapp.web:
    image: spotquoteapp.web
    build:
      context: .
      dockerfile: SpotQuoteApp/src/SpotQuoteApp.Web/Dockerfile
    container_name: spotquoteapp.web
    ports:
      - "443:443"
      - "8080:8080"      
    depends_on:
      - mongodb.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

volumes:
  mongo_data:
