services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb.dev
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
