services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tests

networks:
  tests:

volumes:
  mongo_data:
