name: Build and Publish NuGet Packages

on:
  workflow_dispatch:

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: Framework

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Make script executable
        run: chmod +x ./build-and-publish-nuget.sh

      - name: Run publish script
        run: ./build-and-publish-nuget.sh
