name: Pull Request App Starts

on:
  pull_request:
    branches:
      - main

jobs:
  run-spot-quote-tests-bash:
    name: Run SpotQuoteApp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Start Script
        working-directory: SpotQuoteApp
        run: bash ./Start.sh

      - name: Wait for SpotQuoteApp to start
        working-directory: SpotQuoteApp
        run: |
          echo "Waiting for app to become available on http://localhost:8080..."
          for i in {1..10}; do
            if curl --fail http://localhost:8080; then
              echo "App is up!"
              exit 0
            fi
            echo "Retrying in 5s ($i)..."
            sleep 5
          done
          echo "App failed to start." >&2
          docker compose -f ../docker-compose.yml logs
          exit 1

      - name: Clean up Docker
        if: always()
        working-directory: SpotQuoteApp
        run: docker compose -f ../docker-compose.yml down -v
